[package]
name = "advent_of_code_2019"
description = "Advent of Code solutions for 2019"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
advent_lib = { workspace = true }
anyhow = { workspace = true }
fnv = "1.0.7"
